version: 2

models:
  - name: mart_character_status
    description: Character counts by status for quick health checks.
    columns:
      - name: status
        tests:
          - not_null

  - name: mart_episode_summary
    description: Episode attributes with character counts.
    columns:
      - name: episode_id
        tests:
          - not_null
          - unique

  - name: mart_location_summary
    description: Location attributes with resident counts.
    columns:
      - name: location_id
        tests:
          - not_null
          - unique
