version: 2

models:
  - name: stg_characters
    description: Cleaned character attributes from the Rick and Morty API.
    columns:
      - name: character_id
        description: Character identifier from the API.
        tests:
          - not_null
          - unique
      - name: name
        description: Character name.
      - name: status
        description: Status label from the API (Alive/Dead/unknown).
      - name: species
        description: Species label from the API.
      - name: gender
        description: Gender label from the API.
      - name: origin_name
        description: Origin location name from the API.
      - name: origin_url
        description: Origin location URL from the API.
      - name: location_name
        description: Last known location name from the API.
      - name: location_url
        description: Last known location URL from the API.
      - name: image_url
        description: Image URL for the character.
      - name: character_url
        description: API URL for the character.
      - name: created_at
        description: Record creation timestamp from the API.
      - name: character_type
        description: Character type label from the API with empty strings converted to null.

  - name: stg_episodes
    description: Cleaned episode attributes from the Rick and Morty API.
    columns:
      - name: episode_id
        description: Episode identifier from the API.
        tests:
          - not_null
          - unique
      - name: name
        description: Episode name.
      - name: air_date
        description: Air date string from the API.
      - name: episode_code
        description: Episode code from the API (e.g. S01E01).
      - name: episode_url
        description: API URL for the episode.
      - name: created_at
        description: Record creation timestamp from the API.
      - name: character_count
        description: Number of characters referenced in the episode.

  - name: stg_locations
    description: Cleaned location attributes from the Rick and Morty API.
    columns:
      - name: location_id
        description: Location identifier from the API.
        tests:
          - not_null
          - unique
      - name: name
        description: Location name.
      - name: dimension
        description: Location dimension from the API.
      - name: location_url
        description: API URL for the location.
      - name: created_at
        description: Record creation timestamp from the API.
      - name: location_type
        description: Location type label from the API with empty strings converted to null.
      - name: resident_count
        description: Number of residents referenced for the location.
